# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='title',
        ),
    ]
