# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20180505_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='user',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
